---
- name: "Update Linux Virtual Machine"
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
    purge: true

- name: "Install required packages"
  apt:
    update_cache: true
    name:
      - "lvm2" # Volumes commands: pvcreate, ...
      - "fdupes" # Pulizie varie

- name: "Copy files for /etc/skel: skeleton for new users home directory"
  tags: "config"
  copy:
    src: "files/{{ linux_files }}/etc/skel/{{ item }}"
    dest: "/etc/skel"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - ".bash_logout"
    - ".bashrc"
    - ".profile"

- name: "Copy files for /home/vagrant: home for vagrant user"
  tags: "config"
  copy:
    src: "files/{{ linux_files }}/home/vagrant/{{ item }}"
    dest: "/home/vagrant"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"
  loop:
    - ".bash_logout"
    - ".bashrc"
    - ".profile"

- name: "Copy files for /etc/sudoers.d/vagrant: vagrant as sudoer"
  tags: "config"
  copy:
    src: "{{ linux_files }}/etc/sudoers.d/vagrant"
    dest: "/etc/sudoers.d/vagrant"
    owner: "root"
    group: "root"
    mode: "0440"
...