---
- name: "Update Linux Virtual Machine"
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
    purge: true

- name: "Copy custom profile files for vagrant user"
  tags: "config"
  copy:
    src: "custom/{{ item }}"
    dest: "/home/vagrant"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"
  loop:
    - ".bash_logout"
    - ".bashrc"
    - ".profile"

- name: "Copy custom sudoers file for vagrant user"
  tags: "config"
  copy:
    src: "custom/sudoers"
    dest: "/etc/sudoers.d/vagrant"
    owner: "root"
    group: "root"
    mode: "0440"
...