---
- name: "Update Linux Virtual Machine"
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
    purge: true

#- name: "Copy docker daemon configuration"
#  copy:
#    src: "daemon.json"
#    dest: "/etc/docker/daemon.json"
#    owner: "root"
#    group: "root"
#    mode: "0600"
#
#- name: "Create '/home/vagrant/.docker' directory for vagrant user"
#  file:
#    path: "/home/vagrant/.docker"
#    state: "directory"
#    owner: "vagrant"
#    group: "docker"
#    mode: "0700"
...