Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define('vagrant-linux') do |current|
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2222, auto_correct: false)
    current.vm.network('private_network', ip: '192.168.56.11')
    current.vm.hostname = 'vagrant-linux'
    add_disk(config, '/home/xpuser/mauro-quaglia/linux-rookie/ansible/disks/disk-b.vdi', 256)
    #add_disk(config, 'disks/disk-c.vdi', 256)
  end
end

def add_disk(config, disk_path, size)
  config.vm.provider "virtualbox" do |vb|
    unless File.exist?(disk_path)
      vb.customize ["createhd", "--filename", disk_path, "--size", size]
    end
    # Collega il disco alla macchina virtuale
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", disk_path]
  end
end