Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define('vagrant-linux') do |current|
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2222, auto_correct: false)
    current.vm.network('private_network', ip: '192.168.56.11')
    current.vm.hostname = 'vagrant-linux'
  end
end